# =============================================
# theme.toml
# =============================================

[flavor]
dark  = ""
light = ""

# --- Manager ---

[manager]

[status]

# --- Which ---

[which]

# --- Confirm ---

[confirm]

# --- Notification ---

[notify]

# --- Input ---

[input]

# --- Tasks ---

[tasks]
